# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: chdoctest
site_url: https://hettlage.github.io/doctesting
theme:
  name: material
  custom_dir: custom_docs_theme
extra:
  version:
    provider: mike
    alias: true
